// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw93e3jl2E_uTI9vnrFdO8j3rfrEpTIpQ',
    appId: '1:901868140405:web:58682f2afed672ce2d053c',
    messagingSenderId: '901868140405',
    projectId: 'school-sports-portal',
    authDomain: 'school-sports-portal.firebaseapp.com',
    storageBucket: 'school-sports-portal.firebasestorage.app',
    measurementId: 'G-PH506WN857',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4kIqAazlSr4dmqG8JhQ2x8JCTSfoTJPQ',
    appId: '1:901868140405:android:d4329a15e6a869782d053c',
    messagingSenderId: '901868140405',
    projectId: 'school-sports-portal',
    storageBucket: 'school-sports-portal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoXkx1xfXI5ZQVHHouK6bKqbPVMOcHj-8',
    appId: '1:901868140405:ios:6108b33fddb441112d053c',
    messagingSenderId: '901868140405',
    projectId: 'school-sports-portal',
    storageBucket: 'school-sports-portal.firebasestorage.app',
    androidClientId: '901868140405-h7dmao8guk1ilcknlapjkvh61scv6njn.apps.googleusercontent.com',
    iosClientId: '901868140405-12advup67o94265iqit884ud4i1q4r9g.apps.googleusercontent.com',
    iosBundleId: 'com.example.sportsFixturesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoXkx1xfXI5ZQVHHouK6bKqbPVMOcHj-8',
    appId: '1:901868140405:ios:6108b33fddb441112d053c',
    messagingSenderId: '901868140405',
    projectId: 'school-sports-portal',
    storageBucket: 'school-sports-portal.firebasestorage.app',
    androidClientId: '901868140405-h7dmao8guk1ilcknlapjkvh61scv6njn.apps.googleusercontent.com',
    iosClientId: '901868140405-12advup67o94265iqit884ud4i1q4r9g.apps.googleusercontent.com',
    iosBundleId: 'com.example.sportsFixturesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw93e3jl2E_uTI9vnrFdO8j3rfrEpTIpQ',
    appId: '1:901868140405:web:ff362b380adecef32d053c',
    messagingSenderId: '901868140405',
    projectId: 'school-sports-portal',
    authDomain: 'school-sports-portal.firebaseapp.com',
    storageBucket: 'school-sports-portal.firebasestorage.app',
    measurementId: 'G-36PC39PMV7',
  );
}
